name: adapt_size
description: "A lightweight responsive utility for scaling widgets, text, and layout based on screen size and device type (mobile, tablet, desktop)."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
